In [1]:
l1=[11,22,33,44,55]
l2=[12,23,34,45,56]
l1+l2

[11, 22, 33, 44, 55, 12, 23, 34, 45, 56]

In [3]:
import numpy as np
l11=np.array(l1)
l22=np.array(l2)
l11+l22

array([ 23,  45,  67,  89, 111])

In [19]:
import pandas as pd
n=[11,22,33,44,55]
s=[i*i for i in m]
c=[i*i*i for i in m]
d=zip(n,s,c)
df=pd.DataFrame(d,columns=['number','square','cube'])

ft=df.drop('number',axis=1)
ft


square    cube
0     121    1331
1     484   10648
2    1089   35937
3    1936   85184
4    3025  166375

In [21]:
#series
df['square']

0     121
1     484
2    1089
3    1936
4    3025
Name: square, dtype: int64

In [22]:
#dataframes
df[['square']]

square
0     121
1     484
2    1089
3    1936
4    3025

In [24]:
#dataframe
print(df[['square']])
#series
df['square']

   square
0     121
1     484
2    1089
3    1936
4    3025


0     121
1     484
2    1089
3    1936
4    3025
Name: square, dtype: int64

In [26]:
print(type(df[['square']]))
type(df['square'])

<class 'pandas.core.frame.DataFrame'>


pandas.core.series.Series

In [27]:
df.cube

0      1331
1     10648
2     35937
3     85184
4    166375
Name: cube, dtype: int64

In [28]:
c1=['number','cube']
df[c1]

number    cube
0      11    1331
1      22   10648
2      33   35937
3      44   85184
4      55  166375

- All values comes in an array 
- Array means it is a list of elements only represnts using numpy pacakge Generally elements present in 4 ways 
- List : Basic represntations 
- Numpy array : Array with Numpy package 
- Tensors : Tensorflow package 
- Torch : Pytorch package 


**Step-10**
- Save the dataframe 
- Dataframes we can save in two formats 
- csv : comma seperated value 
- xlsx : excel format 
- In order to save any data 
- Where you want to save : directory name 
- what is the name of the file for storing 
- what is the extension 
- we already seen same in file handling session 


In [33]:

l1=[12,23,34,45]
l2=[1,2,3,4]


In [34]:
import numpy as np
l11=np.array(l1)
l22=np.array(l2)
l11+l22

array([13, 25, 37, 49])

In [35]:
df['number'].values

array([11, 22, 33, 44, 55], dtype=int64)

In [36]:
df['number']=df['number'].values
df

number  square    cube
0      11     121    1331
1      22     484   10648
2      33    1089   35937
3      44    1936   85184
4      55    3025  166375

**saving the dataframe**
- dataframes can be saved in 2 ways they are
- * cs=comma separated values
  * xlsx=excel format
- in order to save the data
- where u want to save :directory name
- what is the name of the file for storing
- what is the eextension
  

In [37]:
df.to_csv('data.csv')

In [43]:
df.to_excel('excel_data.xlsx')

In [44]:
import pandas as pd
pd.read_csv('data.csv')

Unnamed: 0  number  square    cube
0           0      11     121    1331
1           1      22     484   10648
2           2      33    1089   35937
3           3      44    1936   85184
4           4      55    3025  166375

In [46]:
import pandas as pd
pd.read_excel('excel_data.xlsx')

Unnamed: 0  number  square    cube
0           0      11     121    1331
1           1      22     484   10648
2           2      33    1089   35937
3           3      44    1936   85184
4           4      55    3025  166375

In [47]:
import os
os.getcwd()

'C:\\Users\\Swetha\\Documents\\DS_courses\\EDA_python'

**step12**
- while saving the dataframe
- automatically a new column will create by default
- we should avoid while saving
- permission denied that means the data file should close then save it again

In [52]:
df.to_csv('data2.csv',index=False)
df.to_excel('data3.xlsx',index=False)

In [49]:
import pandas as pd
pd.read_csv('data2.csv')

Unnamed: 0  number  square    cube
0           0      11     121    1331
1           1      22     484   10648
2           2      33    1089   35937
3           3      44    1936   85184
4           4      55    3025  166375

In [54]:
import pandas as  pd
pd.read_excel('data3.xlsx')

number  square    cube
0      11     121    1331
1      22     484   10648
2      33    1089   35937
3      44    1936   85184
4      55    3025  166375